/*
 Navicat Premium Data Transfer

 Source Server         : HS_SMDCTEST138
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Schema         : MDSYS

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 02/06/2023 08:39:37
*/


-- ----------------------------
-- Table structure for HS_ACCESS_JXMDB
-- ----------------------------
DROP TABLE "MDSYS"."HS_ACCESS_JXMDB";
CREATE TABLE "MDSYS"."HS_ACCESS_JXMDB" (
  "EQUIPNO" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "EQUIPNAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
  "NO" VARCHAR2(25 BYTE) VISIBLE,
  "DIFFPRESSUREVALUE" VARCHAR2(50 BYTE) VISIBLE,
  "DIFFPRESSUREJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "TESTPRESSURE" VARCHAR2(50 BYTE) VISIBLE,
  "ACCESSTIME" DATE VISIBLE,
  "CODE" VARCHAR2(50 BYTE) VISIBLE,
  "MODEL" VARCHAR2(50 BYTE) VISIBLE,
  "USERNAME" VARCHAR2(50 BYTE) VISIBLE,
  "TOTALJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "MAJORLEAKAGEJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "CALIBRATIONJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "NITROGENANDJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "TOPSCREWJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "TOPEDGESCREWJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "DETERMINATIONOFWELDSEAM" VARCHAR2(50 BYTE) VISIBLE,
  "VERTICALWELDSEAMJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "HANGINGPOINTJUDGMENT" VARCHAR2(50 BYTE) VISIBLE,
  "LEAKAGERATEM" VARCHAR2(50 BYTE) VISIBLE,
  "LEAKAGERATEL" VARCHAR2(50 BYTE) VISIBLE,
  "LEAKAGERATEOFWELDSEAM" VARCHAR2(50 BYTE) VISIBLE,
  "WELDLEAKAGERATE" VARCHAR2(50 BYTE) VISIBLE,
  "LEAKAGERATEOFPOINT" VARCHAR2(50 BYTE) VISIBLE,
  "LARGELEAKAGESTANDARD" VARCHAR2(50 BYTE) VISIBLE,
  "LARGELEAKAGEVALUE" VARCHAR2(50 BYTE) VISIBLE,
  "TOPSCREWDATADIAMETER" VARCHAR2(50 BYTE) VISIBLE,
  "TOPEDGESCREWDATADIAMETER" VARCHAR2(50 BYTE) VISIBLE,
  "TRANSVERSEWELDDATAPATH" VARCHAR2(50 BYTE) VISIBLE,
  "VERTICALWELDDATAPATH" VARCHAR2(50 BYTE) VISIBLE,
  "HANGINGPOINTDATAPATH" VARCHAR2(50 BYTE) VISIBLE,
  "ID" NUMBER VISIBLE DEFAULT NULL NOT NULL,
  "INVORG" NUMBER VISIBLE NOT NULL,
  "CREATEDATA" DATE VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."EQUIPNO" IS '设备编码';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."EQUIPNAME" IS '设备名称';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."NO" IS 'Id';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."DIFFPRESSUREVALUE" IS '差压值';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."DIFFPRESSUREJUDGMENT" IS '差压判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."TESTPRESSURE" IS '测试压力';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."ACCESSTIME" IS '时间';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."CODE" IS '条码';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."MODEL" IS '型号';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."USERNAME" IS '操作人员';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."TOTALJUDGMENT" IS '总判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."MAJORLEAKAGEJUDGMENT" IS '大漏判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."CALIBRATIONJUDGMENT" IS '标定判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."NITROGENANDJUDGMENT" IS '氮氢判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."TOPSCREWJUDGMENT" IS '顶面螺钉判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."TOPEDGESCREWJUDGMENT" IS '顶边螺钉判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."DETERMINATIONOFWELDSEAM" IS '横焊缝判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."VERTICALWELDSEAMJUDGMENT" IS '竖焊缝判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."HANGINGPOINTJUDGMENT" IS '吊点判定';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."LEAKAGERATEM" IS '顶面螺钉漏率';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."LEAKAGERATEL" IS '顶边螺钉漏率';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."LEAKAGERATEOFWELDSEAM" IS '横焊缝漏率';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."WELDLEAKAGERATE" IS '竖焊缝漏率';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."LEAKAGERATEOFPOINT" IS '吊点漏率';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."LARGELEAKAGESTANDARD" IS '大漏标准';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."LARGELEAKAGEVALUE" IS '大漏值';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."TOPSCREWDATADIAMETER" IS '顶面螺钉数据径';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."TOPEDGESCREWDATADIAMETER" IS '顶边螺钉数据径';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."TRANSVERSEWELDDATAPATH" IS '横焊缝数据路径';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."VERTICALWELDDATAPATH" IS '竖焊缝数据路径';
COMMENT ON COLUMN "MDSYS"."HS_ACCESS_JXMDB"."HANGINGPOINTDATAPATH" IS '吊点数据路径';

-- ----------------------------
-- Primary Key structure for table HS_ACCESS_JXMDB
-- ----------------------------
ALTER TABLE "MDSYS"."HS_ACCESS_JXMDB" ADD CONSTRAINT "SYS_C007488" PRIMARY KEY ("EQUIPNO");

-- ----------------------------
-- Checks structure for table HS_ACCESS_JXMDB
-- ----------------------------
ALTER TABLE "MDSYS"."HS_ACCESS_JXMDB" ADD CONSTRAINT "SYS_C007483" CHECK ("EQUIPNO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MDSYS"."HS_ACCESS_JXMDB" ADD CONSTRAINT "SYS_C007484" CHECK ("EQUIPNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MDSYS"."HS_ACCESS_JXMDB" ADD CONSTRAINT "SYS_C007485" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MDSYS"."HS_ACCESS_JXMDB" ADD CONSTRAINT "SYS_C007486" CHECK ("INVORG" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "MDSYS"."HS_ACCESS_JXMDB" ADD CONSTRAINT "SYS_C007487" CHECK ("CREATEDATA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
